name: Android CI

on:
  push:
    tags:
      - 'v*' # Trigger on any push that starts with v, e.g. v1.0, v1.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/HorizonCam.apk
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
